"""update nullalble in database

Revision ID: 597a2814d650
Revises: 7c1fbcfb7f0f
Create Date: 2026-07-18 01:03:54.862421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597a2814d650'
down_revision: Union[str, Sequence[str], None] = '7c1fbcfb7f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
