"""adding comment & quiz_attempt & user_identity model

Revision ID: 63b183b7073b
Revises: 92f8db616d58
Create Date: 2026-08-23 15:10:03.624197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b183b7073b'
down_revision: Union[str, Sequence[str], None] = '92f8db616d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'ABANDONED', name='quizattemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_attempt_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_quiz_attempt_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempt')),
    sa.UniqueConstraint('quiz_id', 'student_id', 'attempt_no', name='uq_quiz_attempt_quiz_student_number')
    )
    op.create_index('ix_quiz_attempt_student_quiz_status', 'quiz_attempt', ['student_id', 'quiz_id', 'status'], unique=False)
    op.create_table('user_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_identity_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identity')),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_user_identity_provider_provider_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_identity_user_provider')
    )
    op.create_index('ix_user_identity_user_id', 'user_identity', ['user_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_content.id'], name=op.f('fk_comment_lesson_content_id_lesson_content')),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('fk_comment_parent_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_index('ix_comment_lesson_content_created_at', 'comment', ['lesson_content_id', 'created_at'], unique=False)
    op.create_index('ix_comment_parent_id', 'comment', ['parent_id'], unique=False)
    op.create_index('ix_comment_user_id', 'comment', ['user_id'], unique=False)
    op.add_column('quiz_submission', sa.Column('quiz_attempt_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_quiz_submission_quiz_id'), 'quiz_submission', type_='unique')
    op.create_unique_constraint(op.f('uq_quiz_submission_quiz_attempt_id'), 'quiz_submission', ['quiz_attempt_id'])
    op.drop_constraint(op.f('fk_quiz_submission_student_id_user'), 'quiz_submission', type_='foreignkey')
    op.drop_constraint(op.f('fk_quiz_submission_quiz_id_quizzes'), 'quiz_submission', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_submission_quiz_attempt_id_quiz_attempt'), 'quiz_submission', 'quiz_attempt', ['quiz_attempt_id'], ['id'])
    op.drop_column('quiz_submission', 'attempt_no')
    op.drop_column('quiz_submission', 'student_id')
    op.drop_column('quiz_submission', 'quiz_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submission', sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quiz_submission', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quiz_submission', sa.Column('attempt_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_quiz_submission_quiz_attempt_id_quiz_attempt'), 'quiz_submission', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quiz_submission_quiz_id_quizzes'), 'quiz_submission', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('fk_quiz_submission_student_id_user'), 'quiz_submission', 'user', ['student_id'], ['id'])
    op.drop_constraint(op.f('uq_quiz_submission_quiz_attempt_id'), 'quiz_submission', type_='unique')
    op.create_unique_constraint(op.f('uq_quiz_submission_quiz_id'), 'quiz_submission', ['quiz_id', 'student_id', 'attempt_no'], postgresql_nulls_not_distinct=False)
    op.drop_column('quiz_submission', 'quiz_attempt_id')
    op.drop_index('ix_comment_user_id', table_name='comment')
    op.drop_index('ix_comment_parent_id', table_name='comment')
    op.drop_index('ix_comment_lesson_content_created_at', table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_user_identity_user_id', table_name='user_identity')
    op.drop_table('user_identity')
    op.drop_index('ix_quiz_attempt_student_quiz_status', table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    # ### end Alembic commands ###
