"""update database schema

Revision ID: 7c1fbcfb7f0f
Revises: 
Create Date: 2026-07-18 00:18:06.774960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1fbcfb7f0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_time_limit', sa.Float(), nullable=False),
    sa.Column('default_memory_limit', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language')),
    sa.UniqueConstraint('name', name=op.f('uq_language_name'))
    )
    op.create_table('problem_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_tag'))
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_table('reading_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_content'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('BANNED', 'UNVERIFIED', 'ACTIVE', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('JOIN', 'INTERVIEW', 'SOMETHING', name='actiontype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('do_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('interview_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('INTERN', 'FRESHER', 'JUNIOR', 'SENIOR', name='interviewlevel'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_interview_session_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_session'))
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_notification_sender_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_table('quiz_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_enrollment_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_quiz_enrollment_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_enrollment'))
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_quizzes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_table('quiz_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_submission_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_quiz_submission_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_submission'))
    )
    op.create_table('student_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('linkedln_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_student_profile_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_student_profile'))
    )
    op.create_table('teacher_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('school_address', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_teacher_profile_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_teacher_profile'))
    )
    op.create_table('teacher_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('cccd', sa.String(), nullable=False),
    sa.Column('cccd_front_url', sa.String(), nullable=True),
    sa.Column('cccd_back_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AGREE', 'REJECT', 'PENDING', name='teacherregisterstatus'), nullable=False),
    sa.Column('reviewed_note', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_teacher_register_reviewed_by_user')),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('fk_teacher_register_teacher_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_register')),
    sa.UniqueConstraint('cccd', name=op.f('uq_teacher_register_cccd'))
    )
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_history'))
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('thumbnai_url', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'ARCHIVED', name='coursestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.user_id'], name=op.f('fk_courses_teacher_id_teacher_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('slug', name=op.f('uq_courses_slug'))
    )
    op.create_table('interview_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], name=op.f('fk_interview_message_session_id_interview_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_message'))
    )
    op.create_table('interview_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], name=op.f('fk_interview_reports_session_id_interview_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_reports'))
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('sample_input', sa.Text(), nullable=True),
    sa.Column('sample_output', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='problemdifficulty'), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.user_id'], name=op.f('fk_problem_teacher_id_teacher_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem'))
    )
    op.create_index(op.f('ix_problem_slug'), 'problem', ['slug'], unique=True)
    op.create_index(op.f('ix_problem_teacher_id'), 'problem', ['teacher_id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_options_question_id_quiz_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_options'))
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollment_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_enrollment_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment'))
    )
    op.create_table('problem_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('time_limit_ms', sa.Float(), nullable=False),
    sa.Column('memory_limit_mb', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_problem_config_language_id_language')),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_problem_config_problem_id_problem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_config')),
    sa.UniqueConstraint('problem_id', 'language_id', name='uq_problem_config_problem_language')
    )
    op.create_table('problem_tag_map',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_problem_tag_map_problem_id_problem')),
    sa.ForeignKeyConstraint(['tag_id'], ['problem_tag.id'], name=op.f('fk_problem_tag_map_tag_id_problem_tag')),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id', name=op.f('pk_problem_tag_map'))
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_sections_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections'))
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILE_ERROR', name='problemsubmissionstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('runtime_ms', sa.Float(), nullable=False),
    sa.Column('memory_kb', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_submission_language_id_language')),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_submission_problem_id_problem')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_submission_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission'))
    )
    op.create_table('testcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input_file', sa.String(), nullable=False),
    sa.Column('output_file', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_testcase_problem_id_problem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testcase'))
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'TRANSFER', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'PENDING', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('payos_code', sa.String(), nullable=True),
    sa.Column('payos_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_transaction_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    sa.UniqueConstraint('payos_code', name=op.f('uq_transaction_payos_code')),
    sa.UniqueConstraint('transaction_code', name=op.f('uq_transaction_transaction_code'))
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_lesson_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    op.create_table('submission_result_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('testcase_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILE_ERROR', name='problemsubmissionstatus'), nullable=False),
    sa.Column('runtime_ms', sa.Float(), nullable=False),
    sa.Column('memory_kb', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('fk_submission_result_detail_submission_id_submission')),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcase.id'], name=op.f('fk_submission_result_detail_testcase_id_testcase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_result_detail'))
    )
    op.create_table('lesson_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('READING', 'QUIZ', 'PROBLEM', name='lessoncontenttype'), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_content_lesson_id_lesson')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_content'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_content.id'], name=op.f('fk_comment_lesson_content_id_lesson_content')),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('fk_comment_parent_id_comment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('lesson_content_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('lesson_content_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], name=op.f('fk_lesson_content_progress_enrollment_id_enrollment')),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_content.id'], name=op.f('fk_lesson_content_progress_lesson_content_id_lesson_content')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_content_progress')),
    sa.UniqueConstraint('enrollment_id', 'lesson_content_id', name='uq_lesson_content_progress_enrollment_content')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_content_progress')
    op.drop_table('comment')
    op.drop_table('lesson_content')
    op.drop_table('submission_result_detail')
    op.drop_table('lesson')
    op.drop_table('transaction')
    op.drop_table('testcase')
    op.drop_table('submission')
    op.drop_table('sections')
    op.drop_table('problem_tag_map')
    op.drop_table('problem_config')
    op.drop_table('enrollment')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_problem_teacher_id'), table_name='problem')
    op.drop_index(op.f('ix_problem_slug'), table_name='problem')
    op.drop_table('problem')
    op.drop_table('interview_reports')
    op.drop_table('interview_message')
    op.drop_table('courses')
    op.drop_table('user_role')
    op.drop_table('user_history')
    op.drop_table('teacher_register')
    op.drop_table('teacher_profile')
    op.drop_table('student_profile')
    op.drop_table('quiz_submission')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_enrollment')
    op.drop_table('notification')
    op.drop_table('interview_session')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('reading_content')
    op.drop_table('quizzes')
    op.drop_table('problem_tag')
    op.drop_table('language')
    # ### end Alembic commands ###
