"""initial updated database

Revision ID: 92f8db616d58
Revises: 
Create Date: 2026-08-17 20:01:40.119295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f8db616d58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_time_limit', sa.Numeric(), nullable=False),
    sa.Column('default_memory_limit', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language')),
    sa.UniqueConstraint('name', name=op.f('uq_language_name'))
    )
    op.create_table('problem_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_tag')),
    sa.UniqueConstraint('tag_name', name=op.f('uq_problem_tag_tag_name'))
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('passing_score', sa.Numeric(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_table('reading_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_content'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('account_status', sa.Enum('BANNED', 'UNVERIFIED', 'ACTIVE', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('JOIN', 'INTERVIEW', 'TEACHER_APPLICATION_REVIEW', 'COURSE_MODERATION', 'PAYMENT_WEBHOOK', 'PAYOUT_REVIEW', 'ACCOUNT_STATUS_UPDATE', name='auditaction'), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('do_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED', name='coursestatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('fk_courses_teacher_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('slug', name=op.f('uq_courses_slug'))
    )
    op.create_table('interview_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('INTERN', 'FRESHER', 'JUNIOR', 'SENIOR', name='interviewlevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REPORT_GENERATING', 'COMPLETED', 'ABORTED', 'FAILED', name='interviewstatus'), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_interview_session_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_session'))
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'TEACHER_APPLICATION_APPROVED', 'TEACHER_APPLICATION_REJECTED', 'COURSE_APPROVED', 'COURSE_REJECTED', 'JUDGE_RESULT', 'AI_REPORT_READY', 'PAYOUT_APPROVED', 'PAYOUT_REJECTED', name='notificationtype'), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_notification_sender_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('sample_input', sa.Text(), nullable=True),
    sa.Column('sample_output', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='problemdifficulty'), nullable=False),
    sa.Column('passing_score', sa.Numeric(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('fk_problem_teacher_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem')),
    sa.UniqueConstraint('slug', name=op.f('uq_problem_slug'))
    )
    op.create_table('quiz_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_enrollment_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_quiz_enrollment_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_enrollment')),
    sa.UniqueConstraint('quiz_id', 'student_id', name=op.f('uq_quiz_enrollment_quiz_id'))
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('points', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_quizzes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_table('quiz_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_submission_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_quiz_submission_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_submission')),
    sa.UniqueConstraint('quiz_id', 'student_id', 'attempt_no', name=op.f('uq_quiz_submission_quiz_id'))
    )
    op.create_table('student_daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.Column('study_seconds', sa.Integer(), nullable=False),
    sa.Column('solved_problem_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_student_daily_activity_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_daily_activity')),
    sa.UniqueConstraint('student_id', 'activity_date', name=op.f('uq_student_daily_activity_student_id'))
    )
    op.create_table('student_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('learning_preferences', sa.Text(), nullable=True),
    sa.Column('social_links', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_student_profile_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_student_profile'))
    )
    op.create_table('teacher_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('expertise_tags', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('education_entries', sa.Text(), nullable=True),
    sa.Column('experience_entries', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_teacher_profile_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_teacher_profile'))
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('user_id', 'role', name=op.f('uq_user_role_user_id'))
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', name='currency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('fk_wallet_teacher_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet')),
    sa.UniqueConstraint('teacher_id', name=op.f('uq_wallet_teacher_id'))
    )
    op.create_table('course_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_favorite_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_course_favorite_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_favorite')),
    sa.UniqueConstraint('student_id', 'course_id', name=op.f('uq_course_favorite_student_id'))
    )
    op.create_table('course_moderation_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_note', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_moderation_review_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_moderation_review'))
    )
    op.create_table('course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_review_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_course_review_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_review')),
    sa.UniqueConstraint('course_id', 'student_id', name=op.f('uq_course_review_course_id'))
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollment_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_enrollment_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment')),
    sa.UniqueConstraint('student_id', 'course_id', name=op.f('uq_enrollment_student_id'))
    )
    op.create_table('interview_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('AI', 'STUDENT', 'SYSTEM', name='interviewmessagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], name=op.f('fk_interview_message_session_id_interview_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_message'))
    )
    op.create_table('interview_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], name=op.f('fk_interview_reports_session_id_interview_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_reports')),
    sa.UniqueConstraint('session_id', name=op.f('uq_interview_reports_session_id'))
    )
    op.create_table('payout_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_reference', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_payout_request_reviewed_by_user')),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('fk_payout_request_teacher_id_user')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name=op.f('fk_payout_request_wallet_id_wallet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_request'))
    )
    op.create_table('problem_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('time_limit_ms', sa.Numeric(), nullable=False),
    sa.Column('memory_limit_mb', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_problem_config_language_id_language')),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_problem_config_problem_id_problem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_config')),
    sa.UniqueConstraint('problem_id', 'language_id', name=op.f('uq_problem_config_problem_id'))
    )
    op.create_table('problem_tag_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_problem_tag_mapping_problem_id_problem')),
    sa.ForeignKeyConstraint(['tag_id'], ['problem_tag.id'], name=op.f('fk_problem_tag_mapping_tag_id_problem_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_tag_mapping')),
    sa.UniqueConstraint('problem_id', 'tag_id', name=op.f('uq_problem_tag_mapping_problem_id'))
    )
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_options_question_id_quiz_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_options'))
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_sections_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('course_id', 'position', name=op.f('uq_sections_course_id'))
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILE_ERROR', name='problemsubmissionstatus'), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('runtime_ms', sa.Numeric(), nullable=True),
    sa.Column('memory_kb', sa.Numeric(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name=op.f('fk_submission_language_id_language')),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_submission_problem_id_problem')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_submission_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission'))
    )
    op.create_table('teacher_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_profile_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('education_evidence_urls', sa.Text(), nullable=True),
    sa.Column('legal_full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('identity_number', sa.String(), nullable=False),
    sa.Column('identity_front_url', sa.String(), nullable=True),
    sa.Column('identity_back_url', sa.String(), nullable=True),
    sa.Column('selfie_with_id_url', sa.String(), nullable=True),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', name='teacherregisterstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profile.user_id'], name=op.f('fk_teacher_register_teacher_profile_id_teacher_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_register')),
    sa.UniqueConstraint('identity_number', name=op.f('uq_teacher_register_identity_number')),
    sa.UniqueConstraint('teacher_profile_id', name=op.f('uq_teacher_register_teacher_profile_id'))
    )
    op.create_table('testcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input_file', sa.Text(), nullable=False),
    sa.Column('output_file', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_testcase_problem_id_problem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testcase'))
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('payos_code', sa.String(), nullable=True),
    sa.Column('payos_link', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_transaction_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_transaction_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_transaction_idempotency_key')),
    sa.UniqueConstraint('payos_code', name=op.f('uq_transaction_payos_code')),
    sa.UniqueConstraint('transaction_code', name=op.f('uq_transaction_transaction_code'))
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_lesson_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson')),
    sa.UniqueConstraint('section_id', 'position', name=op.f('uq_lesson_section_id'))
    )
    op.create_table('submission_result_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('testcase_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILE_ERROR', name='problemsubmissionstatus'), nullable=False),
    sa.Column('runtime_ms', sa.Numeric(), nullable=True),
    sa.Column('memory_kb', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('fk_submission_result_detail_submission_id_submission')),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcase.id'], name=op.f('fk_submission_result_detail_testcase_id_testcase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_result_detail')),
    sa.UniqueConstraint('submission_id', 'testcase_id', name=op.f('uq_submission_result_detail_submission_id'))
    )
    op.create_table('teacher_register_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_register_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', name='teacherregisterstatus'), nullable=False),
    sa.Column('reviewed_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acted_by'], ['user.id'], name=op.f('fk_teacher_register_history_acted_by_user')),
    sa.ForeignKeyConstraint(['teacher_register_id'], ['teacher_register.id'], name=op.f('fk_teacher_register_history_teacher_register_id_teacher_register')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_register_history'))
    )
    op.create_table('wallet_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('payout_request_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', name='currency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_request.id'], name=op.f('fk_wallet_ledger_payout_request_id_payout_request')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_wallet_ledger_transaction_id_transaction')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name=op.f('fk_wallet_ledger_wallet_id_wallet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_ledger'))
    )
    op.create_table('lesson_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('READING', 'QUIZ', 'PROBLEM', name='lessoncontenttype'), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_content_lesson_id_lesson')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_content')),
    sa.UniqueConstraint('lesson_id', 'content_type', 'content_id', name='uq_lesson_content_lesson_type_content'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_lesson_content_lesson_position')
    )
    op.create_table('lesson_content_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('lesson_content_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], name=op.f('fk_lesson_content_progress_enrollment_id_enrollment')),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_content.id'], name=op.f('fk_lesson_content_progress_lesson_content_id_lesson_content')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_content_progress')),
    sa.UniqueConstraint('enrollment_id', 'lesson_content_id', name=op.f('uq_lesson_content_progress_enrollment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_content_progress')
    op.drop_table('lesson_content')
    op.drop_table('wallet_ledger')
    op.drop_table('teacher_register_history')
    op.drop_table('submission_result_detail')
    op.drop_table('lesson')
    op.drop_table('transaction')
    op.drop_table('testcase')
    op.drop_table('teacher_register')
    op.drop_table('submission')
    op.drop_table('sections')
    op.drop_table('quiz_options')
    op.drop_table('problem_tag_mapping')
    op.drop_table('problem_config')
    op.drop_table('payout_request')
    op.drop_table('interview_reports')
    op.drop_table('interview_message')
    op.drop_table('enrollment')
    op.drop_table('course_review')
    op.drop_table('course_moderation_review')
    op.drop_table('course_favorite')
    op.drop_table('wallet')
    op.drop_table('user_role')
    op.drop_table('teacher_profile')
    op.drop_table('student_profile')
    op.drop_table('student_daily_activity')
    op.drop_table('quiz_submission')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_enrollment')
    op.drop_table('problem')
    op.drop_table('notification')
    op.drop_table('interview_session')
    op.drop_table('courses')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('reading_content')
    op.drop_table('quizzes')
    op.drop_table('problem_tag')
    op.drop_table('language')
    # ### end Alembic commands ###
