"""Drop QuizEnrollmentModel

Revision ID: 94f0978307cd
Revises: 7a4d90c8e2f1
Create Date: 2026-09-06 23:11:18.179945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94f0978307cd'
down_revision: Union[str, Sequence[str], None] = '7a4d90c8e2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_enrollment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_enrollment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_enrollment_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_quiz_enrollment_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_enrollment')),
    sa.UniqueConstraint('quiz_id', 'student_id', name=op.f('uq_quiz_enrollment_quiz_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
