"""add teacher_application_view audit action

Revision ID: d1a7bdc592e9
Revises: 7a4d90c8e2f1
Create Date: 2026-09-05 15:00:19.818729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a7bdc592e9'
down_revision: Union[str, Sequence[str], None] = '7a4d90c8e2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'TEACHER_APPLICATION_VIEW'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
