[project]
name = "judge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cloudian", email = "nguyenkhaan2006@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aio-pika>=10.0.1",
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "rich>=15.0.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn>=0.52.1",
]

[project.scripts]
judge = "judge:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
